### ISSUE TITLE
Importing to eclipse fails (changelog.md can't be accessed)

### ISSUE THREAD

**Issue by Darkhax** [CraftTweaker/CraftTweaker#1018]
#### Issue Description:
When importing the 1.16.1 project into eclipse the build fails. 

#### What happens:
When importing the 1.16.1 project into eclipse the build fails. Apparently it doesn't have permissions to write to the changelog?
https://gist.github.com/Darkhax/ae8ca51435b37c5680dd6e280812f5c9

#### What you expected to happen:

Not this

**Comment by kindlich** [comment]
Make any commit and import again.
I though jared fixed that though...

**Comment by jaredlll08** [comment]
This is a different issue, I fixed the old issue.

This is some obscure issue with Eclipse, I had no luck looking into it since google just gives me different issues.

The TL;DR is:
only happens in eclipse
works fine with running `gradle genGitChangelog`
fails to access the file, if it exists or not.
any possible fix we could come up with wouldn't be a fix with our code, it would be a "make this change to your computer", which isn't a fix.
