### ISSUE TITLE
[1.12.2] Development Environment Crash

### ISSUE THREAD

**Issue by Klebestreifen** [CraftTweaker/CraftTweaker#1056]
#### Issue Description:
CraftTweaker crashes with the current Forge version in the development environment.

#### What happens:
Just now I tried to learn how to develop an extension for CraftTweaker. I found out that the client does not start in the ForgeGradle development environment. Apparently Crafttweaker is not fully compatible with the latest Forge version.

#### What you expected to happen:
Minecraft should start with CraftTweaker in the ForgeGradle 3.+ environment.

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 4.1.20.586
- Using a server: No

**Comment by jaredlll08** [comment]
Honestly I have never seen anyone able to get ForgeGradle 3 working in 1.12.

It was an insane decision by Forge to release a MDK using it when they don't even support 1.12 anymore, so I don't even want to ask in their discord if it is broken because I'm just not going to get anywhere and possibly be banned because I'm asking about 1.12 and not 1.14+.

As it stands, I am not doing anything to make CraftTweaker specifically not work on FG3, but at the same time I'm not going to rewrite my whole 1.12 pipeline to use FG3 just *in case* that is the issue and it now works on FG3 for others.


Just use an old forge MDK from before they started using FG3 for 1.12.
