### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [CraftTweaker/CraftTweaker#1197]
#### What happens:
I change the Minecraft Launcher from MultiMC to ATLauncher. With MultiMC my Modpack works fine. I start the game and the game crashs with "cant create crafttweaker.log file".

#### crafttweaker.log file:  
The file cant be create.

#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: 36.0.43
- CraftTweaker Version: 1.16.5-7.1.0.145
- Are you using a server: no

#### Game log:  
https://pastebin.com/L9XMkmjS

**Comment by kindlich** [comment]
We have an issue template, use it.
Also make sure that your process has access to modify/create the `<minecraft Dir>/logs/crafttweaker.log` file

**Comment by agentwolf88** [comment]
The error is "cant create crafttweaker.log file"

**Comment by kindlich** [comment]
Yes, but filling out the template you would have provided information that is relevant for us to locate the issue.
Like providing the version information at a glance instead of having to shift through the log, as well as whether this is on a server or not.

As already said, check that your process has access to create the crafttweaker.log file, and that your disk has enough space as well.

**Comment by agentwolf88** [comment]
Edited

**Comment by kindlich** [comment]
Thanks.
Can you look into your logs folder and get the latest.log as well as the debug.log (if they exist)?

Please upload them to a pasting site as well instead of uploading them directly 😉 

If the game runs fine with one loader but not with another, it may be possible that it has something to do with file access.
Can you check the access flags as well as the "owner" present on the crafttweaker.log?

**Comment by agentwolf88** [comment]
latest.log: https://paste.ee/p/zqP9R

I think its a macOS thing.

**Comment by jaredlll08** [comment]
Please can someone try with:
https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3287144
and get me a new log

**Comment by jaredlll08** [comment]
Seeing as it has been 2 months and there have been no updates I'm going to close this.

If anyone is still experiencing this, **please** make a new issue or comment on this one.
