### ISSUE TITLE
Move addCurativeItem() to MCPotionEffect

### ISSUE THREAD

**Issue by IchHabeHunger54** [CraftTweaker/CraftTweaker#1199]
**Feature request name**
Move addCurativeItem() from MCPotionEffectInstance to MCPotionEffect

**Feature request description**
Not really a new feature, but I really think that addCurativeItem() should be moved from MCPotionEffectInstance to MCPotionEffect, as that makes more sense. (Currently, MCPotionEffectInstance.addCurativeItem also doesn't work, because it can only be performed on a specific effect instance, effectively making the method useless there.)

**Feature request reason**
as stated above

**Feature request dependencies**
none

**Game Version**
1.16

**Comment by jaredlll08** [comment]
You can't change the curative item on an effect that you don't control (if you are coding a mod and making a custom effect, you can do it, but since these are vanilla effects you can't).

You could use something like the [MCRightClickItemEvent](https://docs.blamejared.com/1.16/en/vanilla/api/event/entity/player/interact/MCRightClickItemEvent/) to detect when a player right clicks your item and then check if they have the effect and remove it.


If I was coding a mod to add more curative items, I would do it through an event.
