### ISSUE TITLE
Could not serialize and be sent to client

### ISSUE THREAD

**Issue by ASlipperySlope** [CraftTweaker/CraftTweaker#1232]
#### Issue Description:  
A console error pops up every time a player joins about not being able to serialize something and that it won't be sent to the client.

#### What happens:  
This error message appears: https://pastebin.com/34bTXAJF

#### What you expected to happen:  
For this to not show up.

#### Script used:  
https://pastebin.com/rVFj8Su7

#### crafttweaker.log file:  
https://pastebin.com/SjwJy1Nx

____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.1.0
- CraftTweaker Version: CraftTweaker-1.16.5-7.1.0.188.jar
- Are you using a server: Yes.
- If yes, does the client have the exact same scripts? Yes.

#### Game log:  
https://pastebin.com/rsgFatJN

**Comment by jaredlll08** [comment]
This isn't an error that is coming from your scripts, this has to do with commands and affects everyone.

**Comment by ASlipperySlope** [comment]
Okay. Is there a way to fix it? Is this a common issue that's being looked into? Kinda left me without a solution here.

**Comment by jaredlll08** [comment]
I think you misunderstood, so firstly, last time I checked there wasn't a fix, I will check again.

Secondly, this ***isn't*** an issue that *you* can fix or need to fix, it has to do with serializing command arguments from the server to the client, so clients don't get a list of arguments to show for auto complete.


If you are actually running into an issue, it isn't caused by this, and we will need more information (like what is happening)

**Comment by ASlipperySlope** [comment]
Ah. I had no idea that that is what that meant. Thank for you the explanation.
