### ISSUE TITLE
[1.16.5 ]Multiple items with same tag

### ISSUE THREAD

**Issue by neroisdabest** [CraftTweaker/CraftTweaker#1282]
I did a recipe in my modpack for an angel ring and it needs glass, but I tried everything and don't know how to write the script so it works with every glass type. I tried .withTag,but it just puts a tag on the item. Can someone help?

**Comment by jaredlll08** [comment]
You are confusing `NBT Tags` with `Tags`. NBT Tags hold information on specific items, like how damaged it is, while Tags are used to group items (what you want).

Hold a piece of glass in your hand, use `/ct hand`, it should give you information on the item, such as what **Item** Tags it is in, so just click the one you want, and use that in the recipe instead of `<item:minecraft:glass>`, it may be: `<tag:items:minecraft:glass>`, but I'm not sure, best to see what the game says.
