### ISSUE TITLE
[Documentation] 1.14 Composter Support Added

### ISSUE THREAD

**Issue by seadoggie01** [CraftTweaker/CraftTweaker#1296]
#### Intro:  
Per [this commit](https://github.com/CraftTweaker/CraftTweaker/commit/3d371a905e8e14eab71a5e9494a1bd35bc7ca1aa), composter support was added to v1.14, but the documentation is missing any mention of the composter. It appears under vanilla/api/misc/Composter/ in v1.16

#### Issue Description:  
Composter docs missing

#### What happens:  
N/A

#### What you expected to happen:  
Expected to see documentation for composters

#### Script used:  
N/A

#### crafttweaker.log file:  
N/A
____
#### Environment:  
All

#### Game log:  
N/A

**Comment by jaredlll08** [comment]
Look I'm going to be honest, 1.14 isn't supported anymore, the only reason the docs are still up is because I have no reason to take them down.

Saying that, I don't want to add new stuff to old docs, I don't want to encourage people to use 1.14, 1.16 is the latest (yes I know 1.17 releases tomorrow) version of the game and that is what people should be using.

**Comment by seadoggie01** [comment]
Wasn't aware it wasn't supported, thanks for the heads up! I would love to use 1.16, but didn't expect most mods to support it. (Most of my favorite modpacks are 1.12 or older) I'll look into 1.16 more

**Comment by jaredlll08** [comment]
Most mods only support 1.16 nowadays, technically 1.15 is the "long term support" from Forge, but honestly I don't know anyone developing for 1.15, it's all 1.16

**Comment by seadoggie01** [comment]
That's great! A few years ago it was all 1.12, glad people are catching up. I'm more of a programmer, but I've dabbled in modpacks a couple times
