### ISSUE TITLE
Unable to remove crafting Quantum Armor    recipes.remove(<ic2:quantum_leggings:26>)

### ISSUE THREAD

**Issue by ParadaAndrey** [CraftTweaker/CraftTweaker#1385]
### Issue description

I wanted to remove the Quantum Armor recipe in order to add a new one. I managed to create a new recipe, but the standard one still works. Help please, I don't know what to do

### Script used

https://gist.github.com/ParadaAndrey/07a0e3fbbed4a3bdf332bd6cd2ce6fc1

### The crafttweaker.log file

https://pastebin.com/gcx8cKfQ

### Minecraft version

1.12

### Forge version

хз

### CraftTweaker version

4.1.20.646

### The latest.log file

there were no failures

**Comment by jaredlll08** [comment]
Try to remove the recipe by it's name?

**Comment by Blue-Beaker** [comment]
I think most IC2 recipes use its own recipe manager instead of the vanilla one, so maybe you should use ic2's own config to disable those recipes.
You can extract industrialcraft-2-xxx.jar/assets/ic2/config/shaped_recipes.ini in ic2 jar file to .minecraft/config/ic2/shaped_recipes.ini and modify it to remove the recipe.

**Comment by jaredlll08** [comment]
Closing due to no reply.
