### ISSUE TITLE
Smithing recipe error 

### ISSUE THREAD

**Issue by LILPRINCES** [CraftTweaker/CraftTweaker#1430]
### Issue description

I tried to use Smithing recipe to make a weapon upgrade function, the jei recipe shows correct but the actual situation is wrong. 
![001](https://user-images.githubusercontent.com/60571513/149567544-499d24d9-9d2b-4d58-83dc-a993ba2eccfb.png)
![002](https://user-images.githubusercontent.com/60571513/149567548-7839f8df-5ef7-4e1c-ac9b-595552bc40e6.png)
![003](https://user-images.githubusercontent.com/60571513/149567551-5cbe417b-ea6e-4589-b45c-cf9554976381.png)
![004](https://user-images.githubusercontent.com/60571513/149567554-ce259059-223d-4a67-8ee9-2f526ab55a1f.png)

### Script used

https://pastebin.com/m6FV8Hfb

### The crafttweaker.log file

https://pastebin.com/xYsuLMwc

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.2

### CraftTweaker version

7.1.2.489

### The latest.log file

https://pastebin.com/xYsuLMwc

**Comment by jaredlll08** [comment]
Smithing recipes use the original input to make the output, this means that it copies the NBT from the input to the output.

JEI shows the correct result because *that* is the *base* item that is being outputted, but because damage is done via NBT, it is transferred from the input item, to the output item when it is crafted, like so:
```java
   public ItemStack getCraftingResult(IInventory inv) {
      ItemStack itemstack = this.result.copy(); // This gets the output that you wrote
      CompoundNBT compoundnbt = inv.getStackInSlot(0).getTag();
      if (compoundnbt != null) {
         itemstack.setTag(compoundnbt.copy()); // This sets the tag on the output to be the tag of the input, including the data.
      }

      return itemstack;
   }
```

Right now there isn't a solution for this, it is just how vanilla handles smithing recipes. I can maybe look into it in the future.
