### ISSUE TITLE
Client unable to connect to server

### ISSUE THREAD

**Issue by Kasax007** [CraftTweaker/CraftTweaker#1447]
### Issue description

Hey, I made a mod pack called "Dreamcraft" for 1.18.1, and I have been getting reports of people not being able to join the server again after a while of playing on it until they restart it. For me, it looks like this issue is related to Crafttweaker and I would love if you could verify that or maybe have an idea where it is coming from. Any help would be highly appreciated. 
The bug report on my mod pack: https://github.com/Kasax007/Modpack-Development/issues/15

I was thinking that this is related to this issue you had before: https://github.com/CraftTweaker/CraftTweaker/issues/944

Thanks in advance
Kasax007

### Steps to reproduce

-Create a server using my mod pack
-Play for a while 
-Disconnect 
-Try to reconnect 

### Script used

https://pastebin.com/ZpHkQM3G

### The crafttweaker.log file

-

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

12.12

### CraftTweaker version

9.0.0+26

### The latest.log file

see github link above

**Comment by jaredlll08** [comment]
> I was thinking that this is related to this issue you had before: https://github.com/CraftTweaker/CraftTweaker/issues/944

Like I said in that issue, it *wasn't* an issue.

It just means that when the client tries to use the commands, they aren't going to get any command suggestions for them, like when you use `/give`, it lists all the items in the game, you won't get that for `/ct give` for example.

*Regardless* I fixed that in a newer CraftTweaker version, you really should update, the latest is `9.0.61`, so you are quite far behind.


As for your actual issue:
```
[20:08:33] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:game_event contains IDs unknown to the receiver!
 - minecraft:click
	at net.minecraft.class_2370.remap(class_2370.java:694) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:283) ~[fabric-registry-sync-v0-0.8.6+533be9ba65-b779c3ab09171f9.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:89) ~[fabric-registry-sync-v0-0.8.6+533be9ba65-b779c3ab09171f9.jar:?]
```

CraftTweaker doesn't even support game event tags yet because we don't see a reason to while they aren't used anywhere, so this isn't us.

**Comment by Kasax007** [comment]
Thanks for your insight on this. Much appreciated! :) 
Also, Crafttweaker is an amazing piece of work considering how simple it makes it for people to add custom stuff to the game.
