### ISSUE TITLE
Won't start at all

### ISSUE THREAD

**Issue by akinmarigold** [CraftTweaker/CraftTweaker#1520]
### Issue description

When I was loading the insane craft modpack once it got loading this it stopped the startup as a whole it also said this was the issue any tips?

### Steps to reproduce

I was just starting up insane crafts latest version which is 1.12.2 on curseforge

### Script used

Idk what this means

### The crafttweaker.log file

I'm not able to be in game.

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

1.12.2

### Other relevant information

Nothing else seems relevant

### The latest.log file

Idk what this is

**Comment by kindlich** [comment]
Several things:

1) Since you are talking about a modpack, I recommend that you first talk to the creators of the modpack, since I have no clue what that pack you are talking about even is? Have you talked to the authors of the pack?
2) Without any of the information provided (log files or scripts used) we cannot really look into what happened.
3) When you wrote `it stopped the startup as a whole`, what exactly are you talking about? Did the game freeze/hang or crash?
4) When you wrote ` it also said this was the issue`, WHERE did it say that CraftTweaker was the issue?

Please at least provide the information provided.
- The crafttweaker.log file can be found inside your `minecraft` directory (the same folder where you can also find the `mods` and `conig` folders
- The latest.log file can be found inside the `logs` folder of your `minecraft` directory.
- Make sure you started the game with enough RAM, as larger modpacks usually require lots of memory...
