### ISSUE TITLE
add crafting requirement of a potion effect

### ISSUE THREAD

**Issue by EnderMelody** [CraftTweaker/CraftTweaker#1540]
### Describe the feature you'd like

would it be possible to add a requirement to a crafting recipe of being under a specific potion effect?

### Additional context

i would like to make the angel ring only be craftable while under the effect of the sunbirds blessing from alex's mobs

### Minecraft version

1.18

### Modloader

Forge

**Comment by jaredlll08** [comment]
Not possible, you don't get a player when you craft the recipes because there may not be a player doing the craft, like in auto crafting systems, or even just the tinkers construct workbench, which you would expect to act like a normal crafting table, but it does not.

RecipeStages does have a mechanic like this (can only craft if you have the stage), but it also has a bunch of workaround solutions to allow auto crafters to work, but those solutions are not viable for the modularity of what you could do with CraftTweaker.
