### ISSUE TITLE
removeSeed not working on tallgrass

### ISSUE THREAD

**Issue by LobaCW** [CraftTweaker/CraftTweaker#1552]
### Issue description

When using removeSeed on a script, it should remove the drop of seeds. but it only remove on grass, it also should work on tallgrass as well, but it doesn't as it keep dropping.

### Steps to reproduce

1. Create a script as provided below (one line only)
2. Harvest tallgrass
3. Notice that seed eventually will drop as it shouldn't (opposite from normal grass)

### Script used

vanilla.seeds.removeSeed(<minecraft:wheat_seeds>);

### The crafttweaker.log file

https://pastebin.com/raw/MBndqepE

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.680

### The latest.log file

https://pastebin.com/raw/64tszne3

**Comment by jaredlll08** [comment]
We simply remove values from the Forge list of seeds to drop <https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/ForgeHooks.java#L187>

Forge only patched `BlockTallGrass` (what you refer to as grass is actually that) to call that method, but not `BlockDoublePlant` (What you refer to as tall grass).

So as you said, it gets removed from the tall grass drops, so CraftTweaker is working perfectly fine, the actual issue is with Forge.

**Comment by LobaCW** [comment]
Oh i see... thanks for the response

Em seg., 12 de set. de 2022 16:40, Jared ***@***.***>
escreveu:
