### ISSUE TITLE
I Crystal and MI Crystal, stack support

### ISSUE THREAD

**Issue by Chromayx** [CraftTweaker/CraftTweaker#1558]
### Describe the feature you'd like

Can you make a little update?
Items
Infusion Crystal and Master Infusion Crystal from Mystical Agriculture are Items that can be used multiply times
like infusion Crystal 1000 times or more and MI Crystal infinite times but if i Shift click on Plus in crafting recipes to craft a whole stack with that it always goes with 1 items item crafting station slots,
Can you make it that the Mod recognizes the I Crystal and MI Crystal as 64 stack Unit?

### Minecraft version

1.12

### Modloader

Forge

**Comment by jaredlll08** [comment]
I have no idea what you're asking here, can you please record a video of the issue so I can understand it better

**Comment by Chromayx** [comment]
i mean i can't craft a whole stack with I Crystal and MI Crystal, this mod thinks these Crystals counts as 1 not as 64

**Comment by Chromayx** [comment]
how  do i put video in here?

**Comment by jaredlll08** [comment]
Can you upload it to YouTube please

**Comment by Chromayx** [comment]
https://www.youtube.com/watch?v=rc_CjGLdH8o

**Comment by jaredlll08** [comment]
Okay, I understand what's going on, you're going to need to report this to either Mystical Agriculture or JEI, but most likely Mystical Agriculture.

The infusion Crystal has a stack size of 1, so when JEI moves the items, it only moves one of each, since that is what it believes is the max amount the player can craft.

There is nothing about this that is related to CraftTweaker, and this is not something that CraftTweaker can fix.
