### ISSUE TITLE
Crash With Woodcutter From Charm

### ISSUE THREAD

**Issue by DistantDig** [CraftTweaker/CraftTweaker#1616]
### Issue description

When trying to pick up an item from the woodcutter's inventory from charm, the client crashes. This issue does not occur when charm is loaded up by itself.

### Steps to reproduce

Install Charm with CraftTweaker (both newest versions), load up a singleplayer world, place a woodcutter down, put an item in and take it back out. Ive only tested it with planks.

### Script used

No scripts need to be loaded in the pack

### The crafttweaker.log file

<script src="https://pastebin.com/embed_js/NJSFwDy2"></script>

### Minecraft version

1.19

### Modloader

Fabric

### Modloader version

Fabric - 0.14.12

### CraftTweaker version

1.19.2-10.1.31

### Other relevant information

Crash log (Hopefully):

<script src="https://pastebin.com/embed_js/je45uCyv"></script>

If I didnt post the pastbit things correctly just let me know

### The latest.log file

<script src="https://pastebin.com/embed_js/yLHaKPvP"></script>

**Comment by jaredlll08** [comment]
Please provide actual links to the files, not the embed links

**Comment by DistantDig** [comment]
Crash Report:
https://pastebin.com/je45uCyv

CraftTweaker Log:
https://pastebin.com/NJSFwDy2

Latest Log:
https://pastebin.com/2sVr8N7R

**Comment by jaredlll08** [comment]
Are you sure this is caused by CraftTweaker and not a different mod? Looking at the log I don't see anything that points to CraftTweaker and looking at the code, I really don't see how CraftTweaker would be breaking this, if it was breaking this, it would also be breaking the stone cutter since they are using the same code.

Loading up Charm into my dev environment also doesn't lead to any issues, can you try with just CraftTweaker and Charm?

**Comment by DistantDig** [comment]
I could have sworn i loaded up minecraft with just CraftTweaker and Charm, but i guess i was mistaken. I managed to narrow it down to another mod, sorry for the mistake.
