### ISSUE TITLE
Modded Profession Custom Trade Crash

### ISSUE THREAD

**Issue by TqLxQuanZ** [CraftTweaker/CraftTweaker#1678]
### Issue description

When trying to modify the trades from modded professions, the server crashes at launch. However, if the scripts were removed at first and reloaded when the server was running, it works fine and the trades are loading fine as well.

It looks like there's something having conflict while the trades are loading up when the server is launching.

### Steps to reproduce

1. Download [Ultimate Car Mod](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod) as it has custom profession from it.
2. Download CraftTweaker-forge-1.18.2-9.1.209.jar as well.
3. Add the script for modifying the gas station attendant trade, any kind of works, the simplest one is just remove all trades from it.
4. Launch the server and wait for it to load.
5. Game crashes.

In single player, it stucks at loading screen with not responding.

### Script used

https://gist.github.com/TqLxQuanZ/dcb6385e8177bb0991c42d71c2652954

### The crafttweaker.log file

There's no log from ct when the game crashes.

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.0 or 40.2.4

### CraftTweaker version

9.1.209

### The latest.log file

https://gist.github.com/TqLxQuanZ/2f7f7cced03c5e66bfb40934dd0eb0d8

**Comment by jaredlll08** [comment]
I think this should be reported to the car mod instead, as it currently stands, no mod would be able to add new trades to their villagers, so if there was an addon for the mod, it couldn't add new trades, which I personally think is a bug that they should fix.

I'll keep this issue open until they have a fix, since I could go out of my way to ensure that this will never be an issue for any mod again, but I would really prefer to not have to be that invasive because one mod doesn't want to fix a bug.

**Comment by TqLxQuanZ** [comment]
You're right, my apologizes, it seems to be working fine with immersive engineering custom professions, looks like car mod only thing. I'll create a ticket on that side.

**Comment by jaredlll08** [comment]
This has been fixed in the Ultimate Car Mod.
