### ISSUE TITLE
[1.18.2] BEPs cannot contain new lines

### ISSUE THREAD

**Issue by Catomax262** [CraftTweaker/CraftTweaker#1703]
### Issue description

Please help, i don't know what BEPs are, i'm new to the mod.

### Steps to reproduce

none

### Script used

https://gist.github.com/Catomax262/af1ee39eeeb448f8fa5b453cb031397e

### The crafttweaker.log file

https://gist.github.com/Catomax262/0685aff2dd099a2932f5dd4783eb0309

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.17

### CraftTweaker version

9.1.211

### The latest.log file

no log issues

**Comment by kindlich** [comment]
Hey there,

BEP is the shorthand for `Bracket Expression Parser`, which is how internally CraftTweaker knows how to resolve `<item:minecraft:air>` (also called a Bracket Expression) into an item/block/tag/... in the game.

The error `BEPs cannot contain new lines` usually means you forgot the closing `>` at the end of one of your Bracket Expressions.
When looking at your script, starting from line 49, most your recipes have Bracket expressions that are not closed properly, for example:
```zs
craftingTable.addShaped("newwoodenpick", <item:minecraft:wooden_pickaxe>, [
    [<item:modestmining:plank>, <item:modestmining:plank>, <item:modestmining:plank],
    [<item:modestmining:fiber>, <item:minecraft:stick>, <item:modestmining:fiber],
    [<item:minecraft:air>, <item:minecraft:stick>, <item:minecraft:air>]
]);
```

Here `<item:modestmining:plank` is not closed with a `>` , so ZenCode will look for the `>` until it reaches the end of the file. Then it will error because Bracket Expressions are not allowed to go over multiple lines of code, which is the error you see.


For more (and probably faster) input I invite you to [join our discord](https://discord.blamejared.com), since more people are online in there than reading through the list of open issues 😉 

I'll close this issue for now but if you have more questions feel free to answer here and I'll reopen the issue.
