### ISSUE TITLE
addJsonRecipe doesn't work properly with botany pots and compact machines

### ISSUE THREAD

**Issue by blockgoblin31** [CraftTweaker/CraftTweaker#1712]
### Issue description

I'm adding recipes to <recipetype:botanypots:crop> with crafttweaker, but any botany pot with one of those recipes is having its GrowthTime set to the invalid value of -1 on reloading the compact machine the pot is placed in. Same as this issue https://github.com/Darkhax-Minecraft/BotanyPots/issues/363 and it does not happen if I print out the MapData my function uses to add the recipe and add a recipe with that data by datapack. 

### Steps to reproduce

1: Install crafttweaker, botany pots, compact machinery, and mystical agriculture
2: use the scripts linked
3: place a botany pot in the compact machine with dirt and a skeleton seed inside it
4: exit and re-enter the compact machine

### Script used

https://gist.github.com/blockgoblin31/af41f0d526a5f9c2d9afad4d5f5b150f

### The crafttweaker.log file

https://gist.github.com/blockgoblin31/1b28862924d3d37071d36d76abc84e11

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.3.0

### CraftTweaker version

10.1.53

### Other relevant information

botany pots 9.0.38
compact machines 5.1.0
only ever recreated with mystical agriculture, though no idea if its actually needed: mystical agriculture 6.0.13

### The latest.log file

https://gist.github.com/blockgoblin31/b003f4f5d690f01e8efc73a83405fcff

**Comment by jaredlll08** [comment]
This is not an issue with CraftTweaker, but rather an issue with how Botany Pots handles crops with multiple soils, as botny pots already has a recipe for skeleton seeds, the above scripts work fine when you change the seed to say `minecraft:bedrock`, or any other item that doesn't have a recipe

A similar issue has been reported here:
https://github.com/Darkhax-Minecraft/BotanyPots/issues/373

Discussion around this issue was had in the [BlameJared discord](https://discord.blamejared.com) here: https://discord.com/channels/136877912698650625/827789353467117569/1211495624957239296
