### ISSUE TITLE
recipe functions for more than just crafting table recipes

### ISSUE THREAD

**Issue by MCBEModder2020** [CraftTweaker/CraftTweaker#1726]
### Describe the feature you'd like

add a recipe function paramater to all vanilla recipe things

### Describe alternatives you've considered

none

### Additional context

for making enchantments carry over through smithing

### Minecraft version

1.20.4

### Modloader

Fabric

**Comment by jaredlll08** [comment]
This is not possible due to how certain machines in vanilla function:

The Furnace, Blast Furnace and Smoker for example function like so:
```java
            ItemStack $$5 = $$1.value().getResultItem($$0);
            ItemStack $$6 = $$2.get(2);
            if ($$6.isEmpty()) {
                $$2.set(2, $$5.copy());
            } else if ($$6.is($$5.getItem())) {
                $$6.grow(1);
            }

**Comment by jaredlll08** [comment]
This is not possible due to how certain machines in vanilla function, for example the Furnace, Blast Furnace and Smoker function like so:
```java
ItemStack recipeOutput = recipe.value().getResultItem(registryAccess);
ItemStack outputSlot = inventory.get(2);
if (outputSlot.isEmpty()) {
    inventory.set(2, recipeOutput.copy());
} else if (outputSlot.is(recipeOutput.getItem())) {
    outputSlot.grow(1);
}
```
To explain, if the output slot is not empty, and it is the same Item (not stack with nbt or count, just base Item), then just grow the output by one.

This actually does introduce a bug currently, where if you have a furnace recipe that outputs 2 apples, the following happens:
1) The first time you smelt it, you get 2 apples
2) The second time it is smelted, you get 1 apple

Forge does fix that though, but Fabric does not.
