### ISSUE TITLE
Any import not working

### ISSUE THREAD

**Issue by KaranMaia** [CraftTweaker/CraftTweaker#1734]
### Issue description

I'm trying to edit the botany recipes with crafttweaker like the guide posted on github (https://github.com/Darkhax-Minecraft/BotanyPots/wiki/CraftTweaker-Support) but when I use that import function it says type not found, do I need to do something prior to that?

And if I use any import, it says type not found for every ocasion, how can I make my import funciont work?

the error: 
![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/73917457/19806cff-e472-47ad-aa68-a4a1ffbf71e7)

### Steps to reproduce

Make the file
Use import
Doesn't work

### Script used

https://pastebin.com/if22FAJL

### The crafttweaker.log file

https://pastebin.com/PBWRTxi3

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.2.30

### CraftTweaker version

14.0.38

### The latest.log file

https://gist.github.com/KaranMaia/d0c4c67598675582009b211099edf489

**Comment by kindlich** [comment]
This is not a CraftTweaker issue.
From what I remember, BotanyPots does no longer have explicit CraftTweaker support.
You can still use CraftTweaker to add botanyPot recipes using the [Generic Recipe Manipulation API](https://docs.blamejared.com/1.20.1/en/mods/other_mods)

If you have more questions, I invite you to join our Discord server, since you'll get help a bit faster over there 😉 
https://discord.blamejared.com/
