### ISSUE TITLE
removeAll() doesn't work

### ISSUE THREAD

**Issue by fyrkantis** [CraftTweaker/CraftTweaker#1754]
### Issue description

I'm trying to remove all recipes of the category "Cutting Board Deploying" from Create: Central Kitchen, using `removeAll()` as in [this example](https://docs.blamejared.com/1.20.1/en/tutorial/Recipes/RecipeManagers):
```
<recipetype:create_central_kitchen:cutting_board_deploying>.removeAll();
```
But after I reload the scripts, all Cutting Board Deploying recipes are still there. Is this an issue with CraftTweaker or something that needs to be fixed in Create: Central Kitchen?

### Script used

https://pastebin.com/h51fADDt

### The crafttweaker.log file

https://pastebin.com/nXsU6yAi

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.3.0

### CraftTweaker version

14.0.40

### The latest.log file

https://pastebin.com/xNXKfEX9

**Comment by Witixin1512** [comment]
Can you try removing the recipes using Farmer's Delight Cutting Board recipe manager? Central Kitchen seems to be pulling recipes from there dynamically, and unlike Create I do not see a `_manual_only` filter in the recipe name.

**Comment by fyrkantis** [comment]
That does seems to work! When I add `<recipetype:farmersdelight:cutting>.removeAll();` it removes all cutting recipes, including the ones I want to remove.
Then it's just the problem of removing them without removing the normal cutting recipes. I tried using `<recipetype:farmersdelight:cutting>.removeByRegex(".+_using_deployer");` but that didn't remove any recipes (I'm guessing it's just looking for farmersdelight recipes and not the ones from Central Kitchen, or I've written the capture wrong). Is the solution to copy all farmersdelight:cutting recipes before removing them, and then re-adding them afterward so they only work for cutting boards? Or is there a less jank solution for this?
Sorry if this is the wrong channel for questions like this, since they aren't related to problems caused by CraftTweaker.

**Comment by Witixin1512** [comment]
I'd go ask Central Kitchen if there is a way to add Cutting Board recipes without them having a deployer equivalent first. If that doesn't work, maybe they can implement something like [Create's](https://github.com/Creators-of-Create/Create/blob/a5dc53ba5f2618515b76dec62bb8b34275c0f445/src/main/java/com/simibubi/create/AllRecipeTypes.java#L143) `_manual_only` filter [here](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/blob/1.20.1/0.5.1-dev/src/main/java/plus/dragons/createcentralkitchen/content/contraptions/deployer/CuttingBoardDeployingRecipe.java#L31), so that you can add Cutting Board recipes that aren't mirrored by the Central Kitchen machine.

**Comment by fyrkantis** [comment]
I'll do that. Thank you for the help!
