### ISSUE TITLE
Trinity

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1781]
### Issue description

These 3 mods
![Screenshot_1](https://github.com/user-attachments/assets/585f66b8-a7ec-4454-9cae-ac29e66f9ad7)
Crashing only on dedicated servers, not lan multiplayer.
Removing one of them (no matter which one) solves the issue.
I tried no mixin version of the SecurityCraft but not solved the issue.

### Script used

Nothing

### The crafttweaker.log file

https://pastebin.com/NNtRbPb1

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

forge-1.12.2-14.23.5.2860

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.700

### The latest.log file

https://pastebin.com/Su39BHsv

**Comment by kindlich** [comment]
This does not look like an issue in CraftTweaker to me.
During the load cycle, builds an internal registry of all existing items so that it can later resolve brackets like `<minecraft:iron_ingot>` into a proper itemStack.

When it asks the Vertical Slab Item for all variants it has, that call errors.
From the error log it seems to me that some versions of Forge don't match with each other.
Try downgrading to e.g. `14.23.5.2854` (which is what the DoubleSlabs mod was built against).

Also, that issue has already been raised on DoubleSlab's side:
https://github.com/CJMinecraft01/DoubleSlabs/issues/277

**Comment by jaredlll08** [comment]
This is most likely an issue with DoubleSlabs calling a client side only method in a non client side only method, so when we call the method, it crashes.

There is nothing for us to do to fix this, they need to fix it.
