### ISSUE TITLE
[Question] How do I get the recipes I added to the custom recipe gui?

### ISSUE THREAD

**Issue by NovaViper** [CraftTweaker/CraftTweaker#293]
#### Issue Description:
I notice when I add in the scripts, none of the recipes appear in the recipe book that's in the crafting table gui nor in the knowledge book

#### What happens:
After I remove the old recipes and add in new ones (replacing them basically), the new recipes do not appear in the recipe book

#### What you expected to happen:
The new recipes to appear in the recipe book and the knowledge book

#### Script used:
All scripts: https://hastebin.com/cagixuneru.scala

CraftTweaker Log: https://hastebin.com/korijetuvo.md

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443
- Crafttweaker: 1.12-4.0.2

#### Your most recent log file where the issue was present: 
Forge Log: https://gist.github.com/NovaViper/149b5f863a2329e1b3925810e26c5afd

**Comment by jaredlll08** [comment]
Did you restart your game?

On Aug 10, 2017 02:49, "Nova Leary" <notifications@github.com> wrote:

Issue Description:

I notice when I add in the scripts, none of the recipes appear in the
recipe book that's in the crafting table gui nor in the knowledge book
What happens:

After I remove the old recipes and add in new ones (replacing them
basically), the new recipes do not appear in the recipe book
What you expected to happen:

The new recipes to appear in the recipe book and the knowledge book
Script used:

All scripts: https://hastebin.com/cagixuneru.scala

CraftTweaker Log: https://hastebin.com/korijetuvo.md
------------------------------
Affected Versions (Do *not* use "latest"):

   - Minecraft: 1.12
   - Forge: 1.12-14.21.1.2443
   - Crafttweaker: 1.12-4.0.2

Your most recent log file where the issue was present:

Forge Log: https://gist.github.com/NovaViper/149b5f863a2329e1b3925810e26c5a
fd

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/CraftTweaker/issues/293>, or mute the thread

**Comment by NovaViper** [comment]
@jaredlll08 I did

**Comment by jaredlll08** [comment]
Update Crt?

**Comment by NovaViper** [comment]
Update Crafttweaker? I have the latest version of the mod

**Comment by jaredlll08** [comment]
you sure?

**Comment by NovaViper** [comment]
I just noticed that there was an update, 4.0.3, <_> I must've not seen it yesterday. The recipes appear now, thanks!
