### ISSUE TITLE
Weird numbers appearing in chat when I load a world + recipes changes not working.

### ISSUE THREAD

**Issue by dragon3025** [CraftTweaker/CraftTweaker#346]
#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): I can't find any in the logs file, and I did a search for it in the modded minecraft folder and it didn't show up.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 1.12.1-forge.1.12.1-14.22.1.2478
- Crafttweaker: CraftTweaker2-1.12-4.0.8

#### Your most recent log file where the issue was present: https://pastebin.com/qHhUrP3U

**Comment by jaredlll08** [comment]
I need the crafttweaker.log

**Comment by dragon3025** [comment]
How do I get it though, it doesn't appear in the logs folder.

**Comment by jaredlll08** [comment]
it isn't in the logs folder.
http://crafttweaker.readthedocs.io/en/latest/#Getting_Started/

**Comment by kindlich** [comment]
First of all, you have an error at line 30: `recipes.remove(<cyclicmagic:uncrafting_block);` (you forgot the `>`)
Second, the issue is that it tries to convert an IItemStack to IData, I believe it's where you multiply the IItemStack at line 37 `recipes.addShapeless(<cyclicmagic:magic_net> * 5, [<randomthings:summoningpendulum>]);`

Try commenting out those two lines

**Comment by dragon3025** [comment]
Oh no wonder, the new issue instructions say to look for minetweaker.log so I didn't notice the crafttweaker.log file in the folder. Here it is: https://pastebin.com/xPxjNEwv

**Comment by jaredlll08** [comment]
It seems that @kindlich figured out the problem.
