### ISSUE TITLE
[1.12.2] CTGUI Made Recipe Not working

### ISSUE THREAD

**Issue by MokahTGS** [CraftTweaker/CraftTweaker#348]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Changing the recipe for ProjectE items using CTGUI made recipe does not seem to work.  New recipes are not loading.  Pressing R to bring up the recipe for the ProjectE item shows the old recipe in JEI.

#### What you expected to happen:
Make a change using CTGUI and on next world load the recipes should be changed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/eZbjRMyS

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/gyF86ftV
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2512
- Crafttweaker: 4.0.8

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by joegman** [comment]
Issue Description:

Removing the furnace recipe for ceramics Porcelain Brick does not work

What happens:

Removing the furnace recipe for porcelain brick using CTGUI and it did not remove it

What you expected to happen:

Make a change using CTGUI and on next world load the recipes should be changed.

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/W9FL41iH

Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/jRLj3jde

Affected Versions (Do not use "latest"):

Minecraft: 1.12.2
Forge: 2512
Crafttweaker: 4.0.8
Your most recent log file where the issue was present:

https://pastebin.com/GXe3vk7a

**Comment by joegman** [comment]
Issue Description:

Attempting to remove a chest recipe from Better With Mods doesn't work.
Note: CTGUI generated slabWood as the ore dictionary value when I wanted sidingWood. Attempting to change it to sidingWood manually results in the same effect

What happens:

Removed a chest recipe using CTGUI, Recipe still exists and all scripts following do not work

What you expected to happen:

CTGUI has the ability to choose between multiple oredict values, recipe is removed

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/i0FPm2jN

Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/rUVfeuyt

Affected Versions (Do not use "latest"):

Minecraft: 1.12.2
Forge: 2512
Crafttweaker: 4.0.8
Your most recent log file where the issue was present:

https://pastebin.com/FyUKTYGh

**Comment by jaredlll08** [comment]
When you say next world load, do you mean a game restart? (close and open)

**Comment by MokahTGS** [comment]
Yes full restart of Minecraft so that recipes should reload.

**Comment by jaredlll08** [comment]
Are you sure that your recipe is correct? looking at the ProjectE source, they don't have the philosopher's stone...

**Comment by MokahTGS** [comment]
Um... In game the stone is there.   The item name is correct.
