### ISSUE TITLE
Unable to create a custom recipe using GTCE tools with oreDict

### ISSUE THREAD

**Issue by navaroneee** [CraftTweaker/CraftTweaker#723]
#### Issue Description:
Unable to create a custom recipe using GTCE tools with oreDict, if I use a tool with any enchant CT reconize and the recipe works 

#### What happens:
IOreDictEntry implementation, MCOreDictEntry, overrides matches() to delegate to contains(), which uses CraftTweakerMC.matches to compare ore dictionary stack with contains' argument stack. But CraftTweakerMC.matches also compares itemstack tags and returns false if they don't match.
 GTCE is registering tools with default tool data NBT and ore dictionary matching always ignore NBT data, but in CT's case, it is taken into account.

#### Script used:
https://pastebin.com/u88aDeQT

#### crafttweaker.log file:
https://pastebin.com/QTq6MLAn (not relevant information)
____
#### Affected Versions : 

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2796
- Crafttweaker: CraftTweaker2-1.12-4.1.11
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 

No results of issue in logs

**Comment by Damien-Reave** [comment]
Just chiming in a month later to note that I'm having the same issue. GTCE team says its Craft Tweaker's fault.

**Comment by Mike-U5** [comment]
I seem to be having a similar issue with Magneticraft.
The recipe shows up just fine in JEI but I cannot actually craft the item.

**Comment by jaredlll08** [comment]
Due to the way that we match oredict, it makes sense for it to check nbt, it is saying "Is this item in the oredict", just like it does when comparing actual items, so I'm not sure what fix I can provide that won't break other things.

Also this won't be a thing in 1.14+, which is going to be the target version very very soon, so any change I make to this won't get the support.

I'm sorry but I don't have a fix that will help everyone.
