### ISSUE TITLE
Issue with furnace.all

### ISSUE THREAD

**Issue by NielsPilgaard** [CraftTweaker/CraftTweaker#757]
#### Issue Description:
`furnace.all` does not respect changes that have been made to furnace recipes, despite `furnace.all` being called after the furnace recipe registry has been modified.

#### What happens:
`furnace.all` gets furnace recipes that do not exist.

#### What you expected to happen:
`furnace.all` to access the changed furnace recipes.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Using `furnace.all`: 
https://gist.github.com/NillerMedDild/5e0e153ff84b1d2a564fb1faa9a2dbbc

Modifying furnace recipes: 
https://gist.github.com/NillerMedDild/372df3f7c7da6ac9a764bbc716419c64
(the function that is used from this script is `purgeItem`)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/NillerMedDild/9fcd5589f09c492a2d485a7e3ec43b8b

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2808
- Crafttweaker: 1.12-4.1.16
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/NillerMedDild/ae3f8f3fddb9449d3c25a12ad7e5d435

**Comment by jaredlll08** [comment]
furnace.all is the current list of furnace recipes at the time of script run, the issue is that actions are delayed till much later in the life cycle (thank Forge for not having a specific place to add Furnace recipes, and thank modders for not using the event if they did have one).

Since actions are delayed till later, the list never gets updated when scripts are running, sorry about that, not much I can really do.

**Comment by NielsPilgaard** [comment]
Dammit, thanks anyway.
