### ISSUE TITLE
crash with husk script

### ISSUE THREAD

**Issue by WarlordWossman** [CraftTweaker/CraftTweaker#796]
#### Issue Description:
Gamecrash when husks die. 
Not entirely sure what's going on here from checking the crashlog.

#### Script used
https://pastebin.com/sEJuY3E8

#### crafttweaker.log file
https://pastebin.com/xTnCASgC

____
#### Affected Versions

- Minecraft: 1.12.2
- Forge: 2838
- Crafttweaker: 4.1.17 

#### Your most recent log file where the issue was present: 
https://pastebin.com/yDa7Xmyj

**Comment by jaredlll08** [comment]
An itemstack can't have a value of 0, which is what you are trying to do on line 6 (between 0 and 2 inclusive)

More info here:
https://github.com/CraftTweaker/CraftTweaker/issues/573

**Comment by WarlordWossman** [comment]
Yeah that makes sense, would it be possible to give an error in the CT log then?
Would make this more clear I guess.

**Comment by jaredlll08** [comment]
We usually do give errors when you do something along the lines of:
```
<minecraft:diamond> * 0
```
since that needs to compile, but with what you're doing, it is being compiled as 
```
<minecraft:diamond>
```
then later when the game is actually running, the amount is applied, you could intheory kill 10 husks, and only crash on the last kill, the previous kills just would have constructed a stack with a bigger value.
