### ISSUE TITLE
Event.player.xp not targeting Levels.

### ISSUE THREAD

**Issue by jelaw21** [CraftTweaker/CraftTweaker#826]
#### Issue Description:
I was attempting to penalize the player upon death by removing 5 levels of their current exp. Meaning, if the player was at level 12, upon respawning after deathing, they would be at level 7.

#### What happens:
When I called `event.player.removeXP(5)` instead of removing 5 levels, it removed a smidgen of xp from the xp accumulated in the bar. Then I tried `event.player.xp` to get and set the levels, and this time tried to remove half of the xp. I was at level 12 with about 2 bars of XP, when I respawned, I lost all 12 levels and only retained the XP in the bar.

#### What you expected to happen:
I expected for the 12 levels to go to 6 when the player respawned.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/g2aFcLvi

You can also reference this converstion on discord between kindlich and myself.
![image](https://user-images.githubusercontent.com/21100827/61176959-05a7b600-a598-11e9-833f-a050947c190e.png)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

As the script runs correctly, craftweaker log was normal.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2(modded) forge-14.23.5.2838
- Crafttweaker: CraftTweaker2-1.12-4.1.19.jar
- Using a server: yes
- If yes, does the client have the exact same scripts? No, was trying to make this a server side script and not have to run another update.

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by VariableVixen** [comment]
It looks like [`player.removeXP()` calls `player.addExperience()`](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/player/MCPlayer.java#L62), whereas right above that [`player.setXP()` uses `player.addExperienceLevel()` instead](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/player/MCPlayer.java#L56) - I think that might be the bug here.

[NINJA EDIT] Setting `player.xp` actually _shouldn't_ do what you want either - a player's "experience" is divided into three types: their total accumulated XP, their XP _this level_, and their level itself (the cost per level increases with the level); accessing "player xp" usually means the first one, sometimes the third, almost _never_ the second.

**Comment by jelaw21** [comment]
So the first script is the more correct script, but still works incorrectly? 
Is there a getter/setter to retrieve a player's level?

**Comment by 0xebjc** [comment]
I was able to accomplish what you want to do by the following code:

	var xpLevelCost = 8;

	If player.xp >= xpLevelCost {
	    	player.xp -= xpLevelCost;
	}

**Comment by jaredlll08** [comment]
`player.xp` returns the experience level
`player.setXP` sets the level, there is no add/remove methods for the level (but you can use the getter and the setter to do `player.xp = player,xp - 5`, which will remove 5 levels.

`player.removeXP` removes xp from the player, not levels, the actual xp in the bar.
there is apparently no `addXP`  method, but you can just remove a negative amount to add xp

I know the names are confusing, but honestly the whole experience system in minecraft is confusing.

Anyway I have no plans on expanding it with more methods in 1.12 since that would mean removing methods and it is way to late to do that.
