### ISSUE TITLE
Unused code bit

### ISSUE THREAD

**Issue by brisingraerowing** [CraftTweaker/CraftTweaker#834]
#### Issue Description:
I found some [useless code](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/commands/Commands.java#L70-L71) in one of the commands (I was looking at them as examples for an addon I'm working on).

Just a bit of a cleanliness issue.

#### What happens:
N/A

#### What you expected to happen:
N/A

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
N/A

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: N/A
- Crafttweaker: git 
- Using a server: N/A
- If yes, does the client have the exact same scripts? N/A

#### Your most recent log file where the issue was present: 
N/A

**Comment by lineargraph** [comment]
Since [the liquid command uses the same lines](https://github.com/CraftTweaker/CraftTweaker/blob/ffb96eba30f7bc2b765414de72c53881d2117a53/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/commands/Commands.java#L94-L95) I think it might be a copy and paste issue. It probably should be replaced by something like

```java
CraftTweakerAPI.game.getItems().sort(ITEM_COMPARATOR)
```
