### ISSUE TITLE
Running into issue with adding a recipe with chickens mod

### ISSUE THREAD

**Issue by phantom1151** [CraftTweaker/CraftTweaker#839]
#### Intro:
I am trying to add a recipe and crafttweaker does not recognize the item properly. im trying to add a recipe for a spawn egg from chickens mod. before you ask yes i have been talking to them about the name of this egg and they are telling me to contact you on the matter. so as i am fighting with them since they are not being helpful i am contacting you so that i can say i have and even maybe you can help.

#### Issue Description:
I am trying to add a recipe and crafttweaker does not recognize the item properly. im trying to add a recipe for a spawn egg from chickens mod.

#### What happens:

it shows in the output for the recipe a black egg that is not usable in anyway

#### What you expected to happen:

it should output a flint, log, quartz, sand, or soulsand egg in my hand

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

`<script src="https://gist.github.com/phantom1151/014a383b6815d4505d3228231768b855.js"></script>`

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge: forge-14.23.5.2838
- Crafttweaker: CraftTweaker2-1.12-4.1.19.jar
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by VariableVixen** [comment]
That... is not even a _little_ bit how you share a gist. First of all, that's an embed script for putting into your own web page. Second, you're supposed to just give a link to the script, not embed it. What you want is to go to the gist itself and copy the URL in your address bar. As it happens, I know how Github does this, so I [can offer the _proper_ link](https://gist.github.com/phantom1151/014a383b6815d4505d3228231768b855) myself here.

Second, the problem is that you're not identifying the egg. Every single recipe you're trying to add will output the same item, `<chickens:spawn_egg>` with no metadata or NBT or _anything_. I don't know how the Chickens mod identifies _which_ chicken a particular egg will spawn, but my recommendation is to spawn in the exact egg you want from creative mode or JEI, hold it in your hand, and run the chat command `/ct hand`. That'll give you the exact identifier for that particular type of egg, which you should then paste in as the recipe output.

**Comment by phantom1151** [comment]
not helpful at all
