### ISSUE TITLE
CraftTweaker-1.14.4-5.0.1.133 dumps recipeTypes when asked to dump recipes

### ISSUE THREAD

**Issue by Syndaryl** [CraftTweaker/CraftTweaker#879]
#### Issue Description:
CraftTweaker-1.14.4-5.0.1.133 dumps recipeTypes when asked to dump recipes

#### What happens:
I type /ct dump recipes, and in ct_dumps recipetype.txt is created. A list of recipe *names* is in the ct log file.
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/3860656/crafttweaker.log)

#### What you expected to happen:
recipe.txt to be created, filled with recipes. Each line would be the CT command to create the recipe, as per 1.12.2 CT.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.14.4
- Forge: 28.1.90
- Crafttweaker: 5.0.1.133
- Using a server: no

#### Your most recent log file where the issue was present: 
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/3860656/crafttweaker.log)

**Comment by jaredlll08** [comment]
I'm having trouble reproducing.

`/ct dump recipes` dumps all the recipes in the game to the crafttweaker.log file

`/ct dump recipeTypes` dumps all the recipe types to the crafttweaker.log file.

all the `/ct dump` sub commands dump to the crafttweaker.log file


the `ct_dumps` folder is used to dump all the values of the bracket handlers, it is more there for plugin developers who want to add auto complete to their plugin.
And there isn't a `<recipe:modid:name>` bracket handler since I don't have a good usecase for it
