### ISSUE TITLE
Recipe don´t Work

### ISSUE THREAD

**Issue by McJJsHD** [CraftTweaker/CraftTweaker#914]
I have made a recipe for an Redstone Reception Coil and it didn´t want to work

[Reception Coil Script.txt](https://github.com/CraftTweaker/CraftTweaker/files/4023817/Reception.Coil.Script.txt)

I made an other Recipe for a Sieve using Botania Ingreedients and it worked, so I`m not sure what the issue is.

I hope someone can help me

the displayed Error is: Cannot cas Zen type native: crafttweaker.item.IItemstack to zen type Native: crafttweaker.data.IData

**Comment by kindlich** [comment]
This issue was closed because you did not follow the template.
I recommend for such questions to rather join the [BlameJared discord server](https://discord.blamejared.com)


In any way, the template is there for a reason.
Though I can already tell you that you misspelt `recipes` and left out some parameters, so of course it's not working.
